version: '3.8'
services:

  app:
    build: .
    container_name: app
    command: uvicorn src.main:app --host 0.0.0.0 --port 8000
    volumes:
      - migrations:/code/alembic/migrations/versions
    expose:
      - 8000
    env_file:
      - .env
    restart: always


  postgres:
    image: postgres:16
    container_name: postgresql-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./psql-initial:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
      - POSTGRES_DB=${DB_NAME}
    expose:
      - 5432
    restart: always

  nginx:
    container_name: nginx
    image: nginx:latest
    ports:
      - "443:443"
      - "8443:8443"
    volumes:
     - /etc/letsencrypt/live/obmenyay-ru.ru/cert.pem:/etc/letsencrypt/live/obmenyay-ru.ru/cert.pem
     - /etc/letsencrypt/live/obmenyay-ru.ru/chain.pem:/etc/letsencrypt/live/obmenyay-ru.ru/chain.pem
     - /etc/letsencrypt/live/obmenyay-ru.ru/fullchain.pem:/etc/letsencrypt/live/obmenyay-ru.ru/fullchain.pem
     - /etc/letsencrypt/live/obmenyay-ru.ru/privkey.pem:/etc/letsencrypt/live/obmenyay-ru.ru/privkey.pem
     - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - app
    restart: always


  redis:
    container_name: redis-db
    image: redis:latest
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - 6379
    restart: always



volumes:
  migrations:
  postgres_data:
